### ISSUE TITLE
Fantasy Endpoint

### ISSUE THREAD

**Issue by akacaio** [mtthai/nba-api-client#2]
Hello Mtthai, there is anyway that we can get this endpoint running?

> https://stats.nba.com/stats/fantasywidget

I've done some modifications, like add the params to the **params.json** and the endpoint configuration at **endpoints.json**

Also add this at **index.js**

``` 	
fantasyStats: function(params, options){ 
        return getDataFromNBA(params, "fantasy_widget", {...default_options, ...options});
}
```

But everytime i try to reach the data, i get this error:

> UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Every data that i try to get from nba.stats.com i got this error, only the local data is available. Can you help me? :)

**Comment by mtthai** [comment]
Hey akacio, I've added the fantasy stats endpoint just now. You can call it with the "fantasyStats" method: 

`nba.fantasyStats({}).then(function(data){
    console.log(data)
})`

This should output every player's fantasy stats. You can filter it by teamid, playerid, season, and any other params listed under the endpoint:

`    "fantasy_stats": {
        "desc": "Fantasy stats and points for all players",
        "params": {
            "LeagueID": "00",
            "Season": "2019-20",
            "SeasonType": "Regular+Season",
            "TodaysPlayers": "N",
            "ActivePlayers": "Y",
            "LastNGames": "10",
            "TodaysOpponent": "0",
            "PlayerID": "",
            "TeamID": "",
            "Location": "",
            "SeasonSegment": "",
            "DateFrom": "",
            "DateTo": "",
            "OpponentTeamID": "",
            "VsConference": "",
            "VsDivision": "",
            "Position": "",
            "PORound": ""
        },
        "url": "https://stats.nba.com/stats/fantasywidget"
    },`

`nba.fantasyStats({TeamID: 1610612745}).then(function(data){
    console.log(data)
})`

I'm guessing the error you were getting was because the endpoint didn't have the required params and it's values. The only real required ones are listed when you visit [https://stats.nba.com/stats/fantasywidget](https://stats.nba.com/stats/fantasywidget) The rest are just extra filters. So yeah, the nba stats site can be really weird and picky sometimes with what params and values are required/accepted. 

Let me know if it's still giving you errors on your end. If it is, add a catch block and post the error message you're getting and we'll try to figure it out.

**Comment by akacaio** [comment]
Hello man, thanks for the reply.

I've done this:

```
const nba = require('nba-api-client');

var options = { formatted: false }
var params = {
  "ActivePlayers":"N",
  "DateFrom":"",
  "DateTo":"",
  "LastNGames":0,
  "LeagueID":"00",
  "Location":"",
  "Month":"",
  "OpponentTeamID":"",
  "PORound":"",
  "PlayerID":"",
  "Position":"",
  "Season":"2019-20",
  "SeasonSegment":"",
  "SeasonType":"Regular+Season",
  "TeamID":"",
  "TodaysOpponent":0,
  "TodaysPlayers":"N",
  "VsConference":"",
  "VsDivision":""
};

  nba.fantasyStats(params, options)
  .then(function(data){ 
    console.log(data) 
  }).catch(function(e){
    console.log("É, deu erro meu querido.", e)
  })
```

And i got this code:

> É, deu erro meu querido. { Error: connect ETIMEDOUT 92.122.239.43:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
>   errno: 'ETIMEDOUT',
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '92.122.239.43',
>   port: 443,
>   config:
>    { adapter: [Function: httpAdapter],
>      transformRequest: { '0': [Function: transformRequest] },
>      transformResponse: { '0': [Function: transformResponse] },
>      timeout: 0,
>      xsrfCookieName: 'XSRF-TOKEN',
>      xsrfHeaderName: 'X-XSRF-TOKEN',
>      maxContentLength: -1,
>      validateStatus: [Function: validateStatus],
>      headers:
>       { Accept: 'application/json, text/plain, */*',
>         'Accept-Encoding': 'Accepflate, sdch',
>         'Accept-Language': 'he-IL,he;q=0.8,en-US;q=0.6,en;q=0.4',
>         'Cache-Control': 'max-age=0',
>         Connection: 'keep-alive',
>         Host: 'stats.nba.com',
>         Referer: 'http://stats.nba.com/',
>         'User-Agent': 'PostmanRuntime/7.4.0' },
>      method: 'get',
>      url:
>       'https://stats.nba.com/stats/fantasywidget?LeagueID=00&Season=2019-20&SeasonType=Regular+Season&TodaysPlayers=N&ActivePlayers=N&LastNGames=0&TodaysOpponent=0&PlayerID=&TeamID=&Location=&SeasonSegment=&DateFrom=&DateTo=&OpponentTeamID=&VsConference=&VsDivision=&Position=&PORound=&Month=&',
>      data: undefined },
>   request:
>    Writable {
>      _writableState:
>       WritableState {
>         objectMode: false,
>         highWaterMark: 16384,
>         finalCalled: false,
>         needDrain: false,
>         ending: false,
>         ended: false,
>         finished: false,
>         destroyed: false,
>         decodeStrings: true,
>         defaultEncoding: 'utf8',
>         length: 0,
>         writing: false,
>         corked: 0,
>         sync: true,
>         bufferProcessing: false,
>         onwrite: [Function: bound onwrite],
>         writecb: null,
>         writelen: 0,
>         bufferedRequest: null,
>         lastBufferedRequest: null,
>         pendingcb: 0,
>         prefinished: false,
>         errorEmitted: false,
>         emitClose: true,
>         bufferedRequestCount: 0,
>         corkedRequestsFree: [Object] },
>      writable: true,
>      _events:
>       [Object: null prototype] {
>         response: [Function: handleResponse],
>         error: [Function: handleRequestError] },
>      _eventsCount: 2,
>      _maxListeners: undefined,
>      _options:
>       { protocol: 'https:',
>         maxRedirects: 21,
>         maxBodyLength: 10485760,
>         path:
>          '/stats/fantasywidget?LeagueID=00&Season=2019-20&SeasonType=Regular+Season&TodaysPlayers=N&ActivePlayers=N&LastNGames=0&TodaysOpponent=0&PlayerID=&TeamID=&Location=&SeasonSegment=&DateFrom=&DateTo=&OpponentTeamID=&VsConference=&VsDivision=&Position=&PORound=&Month=&',
>         method: 'get',
>         headers: [Object],
>         agent: undefined,
>         auth: undefined,
>         hostname: 'stats.nba.com',
>         port: null,
>         nativeProtocols: [Object],
>         pathname: '/stats/fantasywidget',
>         search:
>          '?LeagueID=00&Season=2019-20&SeasonType=Regular+Season&TodaysPlayers=N&ActivePlayers=N&LastNGames=0&TodaysOpponent=0&PlayerID=&TeamID=&Location=&SeasonSegment=&DateFrom=&DateTo=&OpponentTeamID=&VsConference=&VsDivision=&Position=&PORound=&Month=&' },
>      _redirectCount: 0,
>      _redirects: [],
>      _requestBodyLength: 0,
>      _requestBodyBuffers: [],
>      _onNativeResponse: [Function],
>      _currentRequest:
>       ClientRequest {
>         _events: [Object],
>         _eventsCount: 6,
>         _maxListeners: undefined,
>         output: [],
>         outputEncodings: [],
>         outputCallbacks: [],
>         outputSize: 0,
>         writable: true,
>         _last: true,
>         chunkedEncoding: false,
>         shouldKeepAlive: true,
>         useChunkedEncodingByDefault: false,
>         sendDate: false,
>         _removedConnection: false,
>         _removedContLen: false,
>         _removedTE: false,
>         _contentLength: 0,
>         _hasBody: true,
>         _trailer: '',
>         finished: true,
>         _headerSent: true,
>         socket: [TLSSocket],
>         connection: [TLSSocket],
>         _header:
>          'GET /stats/fantasywidget?LeagueID=00&Season=2019-20&SeasonType=Regular+Season&TodaysPlayers=N&ActivePlayers=N&LastNGames=0&TodaysOpponent=0&PlayerID=&TeamID=&Location=&SeasonSegment=&DateFrom=&DateTo=&OpponentTeamID=&VsConference=&VsDivision=&Position=&PORound=&Month=& HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAccept-Encoding: Accepflate, sdch\r\nAccept-Language: he-IL,he;q=0.8,en-US;q=0.6,en;q=0.4\r\nCache-Control: max-age=0\r\nConnection: keep-alive\r\nHost: stats.nba.com\r\nReferer: http://stats.nba.com/\r\nUser-Agent: PostmanRuntime/7.4.0\r\n\r\n',
>         _onPendingData: [Function: noopPendingOutput],
>         agent: [Agent],
>         socketPath: undefined,
>         timeout: undefined,
>         method: 'GET',
>         path:
>          '/stats/fantasywidget?LeagueID=00&Season=2019-20&SeasonType=Regular+Season&TodaysPlayers=N&ActivePlayers=N&LastNGames=0&TodaysOpponent=0&PlayerID=&TeamID=&Location=&SeasonSegment=&DateFrom=&DateTo=&OpponentTeamID=&VsConference=&VsDivision=&Position=&PORound=&Month=&',
>         _ended: false,
>         res: null,
>         aborted: undefined,
>         timeoutCb: null,
>         upgradeOrConnect: false,
>         parser: null,
>         maxHeadersCount: null,
>         _redirectable: [Circular],
>         [Symbol(isCorked)]: false,
>         [Symbol(outHeadersKey)]: [Object] },
>      _currentUrl:
>       'https://stats.nba.com/stats/fantasywidget?LeagueID=00&Season=2019-20&SeasonType=Regular+Season&TodaysPlayers=N&ActivePlayers=N&LastNGames=0&TodaysOpponent=0&PlayerID=&TeamID=&Location=&SeasonSegment=&DateFrom=&DateTo=&OpponentTeamID=&VsConference=&VsDivision=&Position=&PORound=&Month=&' },
>   response: undefined }

Same thing happens if i run this:

```
nba.fantasyStats({TeamID: 1610612745}, options).then(function(data){ console.log(data) }).catch(function(e){
    console.log("Error!", e)
  }) 
```

Don't know if it's a proxy issue here.

**Comment by mtthai** [comment]
Yeah I've tried plucking at it for some time now and it seems like the NBAs blocking requests made through proxies. Also, it may be blocking specific ip addresses now since I can't access the data by inputting the url through the browser directly as it just hangs indefinitely. I definitely was able to access it through the browser earlier today but now it's just not pulling the data now. 

I still have success using it locally using node and through browser apps since I'm using JSONP to bypass CORS. Unfortunately, that's pretty much what we're limited to at the moment. I'll keep trying to find a solution to this but until then, I'll leave this issue open for others to see.

**Comment by akacaio** [comment]
I'll give another try tomorrow at home, because i did some tests at work. The strange thing here is if i access the link directly from notepad, it works. But when it's generated by the generateURL function, i can't access the data either.

If something new comes up i'll update here.

**Comment by akacaio** [comment]
Hey Marvin, did some tests back in home and it did work. Probably it was the proxy issue. Thank you!

**Comment by mtthai** [comment]
Ah cool, I'll go ahead and close this issue then.
