### ISSUE TITLE
having a problem when using certain functions, returns a promise that never loads

### ISSUE THREAD

**Issue by adeola-ak** [mtthai/nba-api-client#4]
having a problem when using certain functions, returns a promise that never loads -- copied code for returning promises and still returning a promise that is "pending" but undefined in my console

**Comment by mambaprogramming** [comment]
yea same dude. Had to use the other nba api to supply this one.

Probably will make my own one that updates this issue

**Comment by adeola-ak** [comment]
hey so did you make your own? yea i wish his was working, i love how simple working with the endpoints wouldve been if all the data returned

**Comment by ptoner** [comment]
Pretty sure it's the user agent it uses to connect.

**Comment by mtthai** [comment]
Yeah sorry this project is pretty much closed, lost interest in keeping up with it. It's most likely the user agent, but haven't found one that works with nba.com. There're other nba api clients out there that I think still work so you're better off using those. I'll keep this issue up for any others that stumble on this project.

**Comment by mtthai** [comment]
Found a working new user agent, so the api should connect now.
